config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post '/graphql', to: 'graphql#query'
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  root to: redirect("/graphiql")


  resources :items
  resources :heros
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hero.rb
class Hero < ApplicationRecord
  has_many :itemizations, dependent: :destroy
  has_many :items, through: :itemizations
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/itemization.rb
class Itemization < ApplicationRecord
  belongs_to :hero
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  skip_before_action :verify_authenticity_token

  def query
    # Execute queries with your schema
    result = Schema.execute(params[:query], variables: params[:variables])
    render json: result
  end
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :set_hero, only: [:show, :edit, :update, :destroy]

  # GET /heros
  # GET /heros.json
  def index
    @heros = Hero.all
  end

  # GET /heros/1
  # GET /heros/1.json
  def show
  end

  # GET /heros/new
  def new
    @hero = Hero.new
  end

  # GET /heros/1/edit
  def edit
  end

  # POST /heros
  # POST /heros.json
  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to @hero, notice: 'Hero was successfully created.' }
        format.json { render :show, status: :created, location: @hero }
      else
        format.html { render :new }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heros/1
  # PATCH/PUT /heros/1.json
  def update
    respond_to do |format|
      if @hero.update(hero_params)
        format.html { redirect_to @hero, notice: 'Hero was successfully updated.' }
        format.json { render :show, status: :ok, location: @hero }
      else
        format.html { render :edit }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heros/1
  # DELETE /heros/1.json
  def destroy
    @hero.destroy
    respond_to do |format|
      format.html { redirect_to heros_url, notice: 'Hero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hero_params
      params.require(:hero).permit(:name, :main_attr, :skill1, :skill2, :skill3, :skill4, :str, :agi, :int)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :cost, :hero_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/heros/_form.html.haml
= form_for @hero do |f|
  - if @hero.errors.any?
    #error_explanation
      %h2= "#{pluralize(@hero.errors.count, "error")} prohibited this hero from being saved:"
      %ul
        - @hero.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :main_attr
    = f.text_field :main_attr
  .field
    = f.label :skill1
    = f.text_field :skill1
  .field
    = f.label :skill2
    = f.text_field :skill2
  .field
    = f.label :skill3
    = f.text_field :skill3
  .field
    = f.label :skill4
    = f.text_field :skill4
  .field
    = f.label :str
    = f.number_field :str
  .field
    = f.label :agi
    = f.number_field :agi
  .field
    = f.label :int
    = f.number_field :int
  .actions
    = f.submit 'Save'

app/views/heros/edit.html.haml
%h1 Editing hero

= render 'form'

= link_to 'Show', @hero
\|
= link_to 'Back', heros_path

app/views/heros/index.html.haml
%h1 Listing heros

%table
  %thead
    %tr
      %th Name
      %th Main attr
      %th Skill1
      %th Skill2
      %th Skill3
      %th Skill4
      %th Str
      %th Agi
      %th Int
      %th
      %th
      %th

  %tbody
    - @heros.each do |hero|
      %tr
        %td= hero.name
        %td= hero.main_attr
        %td= hero.skill1
        %td= hero.skill2
        %td= hero.skill3
        %td= hero.skill4
        %td= hero.str
        %td= hero.agi
        %td= hero.int
        %td= link_to 'Show', hero
        %td= link_to 'Edit', edit_hero_path(hero)
        %td= link_to 'Destroy', hero, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Hero', new_hero_path

app/views/heros/new.html.haml
%h1 New hero

= render 'form'

= link_to 'Back', heros_path

app/views/heros/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @hero.name
%p
  %b Main attr:
  = @hero.main_attr
%p
  %b Skill1:
  = @hero.skill1
%p
  %b Skill2:
  = @hero.skill2
%p
  %b Skill3:
  = @hero.skill3
%p
  %b Skill4:
  = @hero.skill4
%p
  %b Str:
  = @hero.str
%p
  %b Agi:
  = @hero.agi
%p
  %b Int:
  = @hero.int

= link_to 'Edit', edit_hero_path(@hero)
\|
= link_to 'Back', heros_path

app/views/items/_form.html.haml
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :cost
    = f.number_field :cost
  .field
    = f.label :hero
    = f.text_field :hero
  .actions
    = f.submit 'Save'

app/views/items/edit.html.haml
%h1 Editing item

= render 'form'

= link_to 'Show', @item
\|
= link_to 'Back', items_path

app/views/items/index.html.haml
%h1 Listing items

%table
  %thead
    %tr
      %th Name
      %th Cost
      %th Hero
      %th
      %th
      %th

  %tbody
    - @items.each do |item|
      %tr
        %td= item.name
        %td= item.cost
        %td= item.hero
        %td= link_to 'Show', item
        %td= link_to 'Edit', edit_item_path(item)
        %td= link_to 'Destroy', item, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Item', new_item_path

app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/items/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @item.name
%p
  %b Cost:
  = @item.cost
%p
  %b Hero:
  = @item.hero

= link_to 'Edit', edit_item_path(@item)
\|
= link_to 'Back', items_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GraphqlTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>